name = "adventOfCode2022"
version = "0.1.0"
license = "license"
author = "gareth"
maintainer = "gareth@gareth-P410.com"
copyright = "Copyright 2022, gareth"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
[dependencies]
stdlib.git = "https://github.com/fortran-lang/stdlib"
stdlib.branch = "stdlib-fpm"
